<!DOCTYPE html>

<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title> CSC174 Project1 | <?php echo "$currentPage"; ?></title>
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<link rel="stylesheet" href="css/materialize.min.css">
		<link rel="stylesheet" href="css/styles.css">
		<link href="https://fonts.googleapis.com/css?family=Roboto|Russo+One" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Gentium+Book+Basic" rel="stylesheet">
	</head>
	<body>
<!-- Title is now part of the navigation as a logo
	<header>
		<h1 class = "title">
			<a href="index.php">Sports!</a>
		</h1>

	</header>

--> 



